name: Nodejs tests for sphinxql

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop

permissions:
  contents: read

jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: true
      matrix:
        node: [12, 14, 16, 18]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm install
      - name: check code format
        run: npm run format
      - name: Lint code
        run: npm run lint
      - name: test code
        run: npm run test

